export const CHANGE_MODAL_VISIBILITY = 'CHANGE_MODAL_VISIBILITY'

export const CRIAR_CONTA_SUCCESS = 'CRIAR_CONTA_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS'

export const SHOW_LOGIN_FORM = 'SHOW_LOGIN_FORM'
export const SHOW_RECOVER_PASSWORD_FORM = 'SHOW_RECOVER_PASSWORD_FORM'
